### PR TITLE
update vimc architecture and add separate diagrams for orderlyweb

### PR DESCRIPTION
**Pull request by hillalex**

### CODE REVIEW

**Review by richfitz — CHANGES_REQUESTED** [review]
Thanks - this looks great, and simplifies what we have.

In the main diagram, arrows point towards the volume but here you use the opposite order - could you swap them in the new diagram?

Do we want to include the other volumes in the OW diagram too (proxy logs and css)?

**Comment by hillalex** [comment]
Thanks, yep, have added those vols and changed the arrow direction.

**Review by richfitz — APPROVED** [review]
LGTM

**Review by EmmaLRussell — CHANGES_REQUESTED** [review]
Nice! Should the orderly web user cli container be on the OW architecture diagram as well?

The VIMC architecture diagram shows a direct link between OW and the Montagu db, is that right? (It does talk to the Montagu API though...)  'Note 3' above the Orderly Web blob?

**Comment by hillalex** [comment]
Yes, the runner talks to the db. "Note 3" refers to the notes at the bottom! I forgot that the web app also talks to Montagu API, will add that in! I don't think the clis are part of the architecture as such, they're more of a deployment implementation detail.

**Review by EmmaLRussell — APPROVED** [review]

**Pull request merged**
